# Site settings
title: Merrick Sapsford
name: Merrick Sapsford
description: "Engineering Leader"
url: "www.sapsford.tech"

github_username: msaps
linkedin_username: merrick-sapsford-3218b952
cv_url: "http://sapsford.tech/docs/Resume.pdf"
email: merrick@sapsford.tech

avatar: yes
avatar_img_path: "https://avatars0.githubusercontent.com/u/3515448"

front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty
